# Generated by Django 4.0.6 on 2023-12-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint_website', '0002_allorderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='allorderdetail',
            name='delivery_status',
            field=models.BooleanField(default=False),
        ),
    ]
