# Generated by Django 4.0.6 on 2024-05-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint_website', '0005_allorderdetail_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allorderdetail',
            name='delivery_id',
            field=models.CharField(max_length=50),
        ),
    ]
